#!/bin/bash

#Copyright (C) 2016 Isak Eriksson, Patrik Wållgren
#
#This file is part of ResolutionsAnalyzer.
#
#    ResolutionsAnalyzer is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    ResolutionsAnalyzer is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with ResolutionsAnalyzer.  If not, see <http://www.gnu.org/licenses/>.

#gets common ancestor, checkouts left, right, ancestor and result, copies the files to output folder and checkout master again

#$1 path to repo
#$2 merge commit sha-1
#$3 output file
#$4 file to analyze

function resetGit {
	back=$(pwd)
	cd $1
	git rm .gitattributes
	git add -A
	git reset --hard 
	git clean -xdf
	git reset --hard HEAD
	cd $back
}

function pull {
	back=$(pwd)
	cd $1
	git pull origin master
	cd $back
}

function fetchFile {
	#$1 path to repo
	#$2 sha
	#$3 file to fetch
	#$4 output file
	back=$(pwd)
	cd $1
	git checkout $2
	cp $3 $4
	cd $back
}

#resetGit $1
#sleep 0.5
#pull $1
#sleep 0.5
#checkout result
fetchFile $1 $2 $4 $3
