#!/bin/bash

#Copyright (C) 2016 Isak Eriksson, Patrik Wållgren
#
#This file is part of ResolutionsAnalyzer.
#
#    ResolutionsAnalyzer is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    ResolutionsAnalyzer is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with ResolutionsAnalyzer.  If not, see <http://www.gnu.org/licenses/>.

#Creates a file containing the git diff of two commits
#$1: path to CFT files
#$2: left file
#$3: common ancestor
#$4: right file
#$5: path to output file

cd $1
git merge-file -p --diff3 $2 $3 $4 > $5
