#!/bin/bash

#Copyright (C) 2016 Isak Eriksson, Patrik Wållgren
#
#This file is part of ResolutionsAnalyzer.
#
#    ResolutionsAnalyzer is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    ResolutionsAnalyzer is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with ResolutionsAnalyzer.  If not, see <http://www.gnu.org/licenses/>.

#Resets git repository and pulls the latest
#$1: path to repo

cd $1
function resetGit {
	back=$(pwd)
	cd $1
	git rm .gitattributes
	git add -A
	git reset --hard 
	git clean -xdf
	git reset --hard HEAD
	cd $back
}

function pull {
	back=$(pwd)
	cd $1
	git pull origin master
	cd $back
}

resetGit $1
pull $1
